# This is a basic workflow to help you get started with Actions

name: Bibata Cursor

# Controls when the action will run.
on:
  # Triggers the workflow when this definition itself has changed
  push:
    paths:
      - '.github/workflows/bibata-cursor.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Render the base graphics first
  render:

    name: Bitmap${{matrix.shape}}${{matrix.color}}${{matrix.side}}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shape: ['-Modern', '-Classic']
        color: ['-Amber', '-Classic', '-Ice']
        side: ['', '-Right']
      max-parallel: 4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout bibata Repo
        uses: actions/checkout@v4
        with:
          repository: ful1e5/Bibata_Cursor

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn

      - name: Install dependencies
        run: |
          rm yarn.lock
          yarn install

      - name: Enable parallelism
        run: |
          jq 'with_entries(select(.key == "Bibata${{matrix.shape}}${{matrix.color}}${{matrix.side}}"))' render.json > render.json.tmp
          cat render.json.tmp
          mv render.json.tmp render.json

      - name: Render Cursors
        run: yarn run render

      - name: Upload Artifacts (Bitmaps)
        uses: actions/upload-artifact@v4
        with:
          name: partial-bitmaps${{matrix.shape}}${{matrix.color}}${{matrix.side}}
          path: ./bitmaps
          compression-level: 0

  # Collect the rendered artifact for easy download
  render-collect:

    needs: render

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout bibata Repo
        uses: actions/checkout@v4
        with:
          repository: ful1e5/Bibata_Cursor

      - name: Fetch all results
        uses: actions/download-artifact@v4
        with:
          pattern: partial-bitmaps-*
          path: ./bitmaps
          merge-multiple: true

      - name: Deploy license file to bitmap package
        run: cp LICENSE ./bitmaps/

      - name: Amagalation Re-upload
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-bitmaps
          path: ./bitmaps
          compression-level: 0

  # Build cursors by a matrix
  build:

    if: ${{ false }}

    needs: render

    strategy:
      max-parallel: 4
      matrix:
        platform:
          - name: '-Windows'
            arg: 'windows'
          - name: ''
            arg: 'x11'
        shape:
          - name: '-Modern'
            desc: 'rounded edge'
          - name: '-Classic'
            desc: 'sharp edge'
        color:
          - name: '-Amber'
            desc: 'Yellowish'
          - name: '-Classic'
            desc: 'Black'
          - name: '-Ice'
            desc: 'White'
        side:
          - name: ''
            cfg: build.toml
            desc: ''
          - name: -Right
            cfg: build.right.toml
            desc: 'right-hand'


    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout bibata Repo
        uses: actions/checkout@v4
        with:
          repository: ful1e5/Bibata_Cursor

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn

      # No node.js involvement except scripts, skip dependecies
      # - name: Install dependencies
      #   run: |
      #     rm yarn.lock
      #     yarn install

      - name: Acquire rendered bitmaps
        uses: actions/download-artifact@v4
        with:
          name: partial-bitmaps${{matrix.shape}}${{matrix.color}}${{matrix.side}}
          path: ./bitmaps

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # python-version: '3.7'
          check-latest: true

      - name: Install required build dependency clickgen
        run: pip install clickgen

      - name: Convert and Package
        run: yarn run build

      - name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-windows
          path: |
            ./themes/*-Windows
            ./themes/LICENSE
          compression-level: 0

      - name: Upload Artifacts (XCursor)
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-xcursor
          path: |
            ./themes
            ./themes/LICENSE
            !./themes/*-Windows
          compression-level: 9


      - name: Upload Artifacts (Bitmaps)
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-bitmaps
          path: ./bitmaps
          compression-level: 0
