# This is a basic workflow to help you get started with Actions

name: Bibata Cursor

# Controls when the action will run.
on:
  # Triggers the workflow when this definition itself has changed
  push:
    paths:
      - '.github/workflows/bibata.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout bibata Repo
        uses: actions/checkout@v4
        with:
          repository: ful1e5/Bibata_Cursor

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # python-version: '3.7'
          check-latest: true

      - name: Install required build dependency clickgen
        run: pip install clickgen

      - name: Install dependencies
        run: |
          rm yarn.lock
          yarn install

      - name: Render Cursors
        run: yarn run render

      - name: Convert and Package
        run: yarn run build

      - name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-windows
          path: |
            ./themes/*-Windows
            ./themes/LICENSE


      - name: Upload Artifacts (XCursor)
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-xcursor
          path: |
            ./themes
            ./themes/LICENSE
            !./themes/*-Windows


      - name: Upload Artifacts (Bitmaps)
        uses: actions/upload-artifact@v4
        with:
          name: bibata_cursor-bitmaps
          path: ./bitmaps
