# This is a basic workflow to help you get started with Actions

name: cdecl

# Controls when the action will run.
on:
  # Triggers the workflow on push *on all branches*
  # but only when this workflow defition has been changed.
  push:
    paths:
      - '.github/workflows/cdecl.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout cdecl Repo
        uses: actions/checkout@v2
        with:
          repository: paul-j-lucas/cdecl

      - name: Build inside qemu
        uses: uraimo/run-on-arch-action@v2.0.9
        with:
          arch: aarch64
          distro: archarm_latest
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/cdecl"
          run: |
            pacman -Syu --noconfirm --noprogressbar base-devel
            cd /cdecl
            autoreconf -fiv
            ./configure
            make

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build Output
          path: src/cdecl
          if-no-files-found: error